version: '3'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    ports:
      - "9200"
    networks:
      - foodtrucks-es.net
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    healthcheck:
      test: ['CMD-SHELL', 'curl --fail http://localhost:9200/_cluster/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 50

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000"
    depends_on:
      es:
        condition: service_healthy
    networks:
      - foodtrucks-es.net
      - foodtrucks-proxy.net


  nginx-proxy:
    image: nginx:alpine3.17
    ports:
      - 80:80
    networks:
      - foodtrucks-proxy.net
    expose:
      - 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./flask-app/templates:/etc/nginx/templates
      - ./flask-app/static:/usr/share/nginx/html/static
    depends_on:
      flask-app:
        condition: service_started

networks:
  foodtrucks-es.net:
  foodtrucks-proxy.net:

volumes:
    esdata1:
      driver: local